name: kafka_cluster

services:
  kafka-1:
    image: docker.io/bitnami/kafka:${KAFKA_RELEASE_VERSION}
    hostname: ${KAFKA_1_HOSTNAME}
    ports:
      - 9092
    environment:
      KAFKA_TLS_TYPE: ${KAFKA_TLS_TYPE}
      KAFKA_CFG_NODE_ID: ${KAFKA_1_CFG_NODE_ID}
      KAFKA_CLIENT_USERS: ${KAFKA_CLIENT_USERS}
      KAFKA_CFG_LISTENERS: ${KAFKA_CFG_LISTENERS}
      KAFKA_CONTROLLER_USER: ${KAFKA_CONTROLLER_USER}
      KAFKA_CLIENT_PASSWORDS: ${KAFKA_CLIENT_PASSWORDS}
      KAFKA_KRAFT_CLUSTER_ID: ${KAFKA_KRAFT_CLUSTER_ID}
      KAFKA_INTER_BROKER_USER: ${KAFKA_INTER_BROKER_USER}
      KAFKA_CFG_PROCESS_ROLES: ${KAFKA_CFG_PROCESS_ROLES}
      KAFKA_CONTROLLER_PASSWORD: ${KAFKA_CONTROLLER_PASSWORD}
      KAFKA_CERTIFICATE_PASSWORD: ${KAFKA_CERTIFICATE_PASSWORD}
      KAFKA_INTER_BROKER_PASSWORD: ${KAFKA_INTER_BROKER_PASSWORD}
      KAFKA_CFG_ADVERTISED_LISTENERS: ${KAFKA_CFG_ADVERTISED_LISTENERS}
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CFG_CONTROLLER_QUORUM_VOTERS}
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: ${KAFKA_CFG_CONTROLLER_LISTENER_NAMES}
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: ${KAFKA_CFG_INTER_BROKER_LISTENER_NAME}
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL: ${KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL}
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: ${KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL}

    volumes:
      - ./certs/jks/${KAFKA_1_HOSTNAME}.server.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro
      - ./certs/jks/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro

  kafka-2:
    image: docker.io/bitnami/kafka:${KAFKA_RELEASE_VERSION}
    hostname: ${KAFKA_2_HOSTNAME}
    ports:
      - 9092
    environment:
      KAFKA_TLS_TYPE: ${KAFKA_TLS_TYPE}
      KAFKA_CFG_NODE_ID: ${KAFKA_2_CFG_NODE_ID}
      KAFKA_CLIENT_USERS: ${KAFKA_CLIENT_USERS}
      KAFKA_CFG_LISTENERS: ${KAFKA_CFG_LISTENERS}
      KAFKA_CONTROLLER_USER: ${KAFKA_CONTROLLER_USER}
      KAFKA_CLIENT_PASSWORDS: ${KAFKA_CLIENT_PASSWORDS}
      KAFKA_KRAFT_CLUSTER_ID: ${KAFKA_KRAFT_CLUSTER_ID}
      KAFKA_INTER_BROKER_USER: ${KAFKA_INTER_BROKER_USER}
      KAFKA_CFG_PROCESS_ROLES: ${KAFKA_CFG_PROCESS_ROLES}
      KAFKA_CONTROLLER_PASSWORD: ${KAFKA_CONTROLLER_PASSWORD}
      KAFKA_CERTIFICATE_PASSWORD: ${KAFKA_CERTIFICATE_PASSWORD}
      KAFKA_INTER_BROKER_PASSWORD: ${KAFKA_INTER_BROKER_PASSWORD}
      KAFKA_CFG_ADVERTISED_LISTENERS: ${KAFKA_CFG_ADVERTISED_LISTENERS}
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CFG_CONTROLLER_QUORUM_VOTERS}
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: ${KAFKA_CFG_CONTROLLER_LISTENER_NAMES}
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: ${KAFKA_CFG_INTER_BROKER_LISTENER_NAME}
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL: ${KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL}
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: ${KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL}

    volumes:
      - ./certs/jks/${KAFKA_2_HOSTNAME}.server.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro
      - ./certs/jks/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro

  kafka-3:
    image: docker.io/bitnami/kafka:${KAFKA_RELEASE_VERSION}
    hostname: ${KAFKA_3_HOSTNAME}
    ports:
      - 9092
    environment:
      KAFKA_TLS_TYPE: ${KAFKA_TLS_TYPE}
      KAFKA_CFG_NODE_ID: ${KAFKA_3_CFG_NODE_ID}
      KAFKA_CLIENT_USERS: ${KAFKA_CLIENT_USERS}
      KAFKA_CFG_LISTENERS: ${KAFKA_CFG_LISTENERS}
      KAFKA_CONTROLLER_USER: ${KAFKA_CONTROLLER_USER}
      KAFKA_CLIENT_PASSWORDS: ${KAFKA_CLIENT_PASSWORDS}
      KAFKA_KRAFT_CLUSTER_ID: ${KAFKA_KRAFT_CLUSTER_ID}
      KAFKA_INTER_BROKER_USER: ${KAFKA_INTER_BROKER_USER}
      KAFKA_CFG_PROCESS_ROLES: ${KAFKA_CFG_PROCESS_ROLES}
      KAFKA_CONTROLLER_PASSWORD: ${KAFKA_CONTROLLER_PASSWORD}
      KAFKA_CERTIFICATE_PASSWORD: ${KAFKA_CERTIFICATE_PASSWORD}
      KAFKA_INTER_BROKER_PASSWORD: ${KAFKA_INTER_BROKER_PASSWORD}
      KAFKA_CFG_ADVERTISED_LISTENERS: ${KAFKA_CFG_ADVERTISED_LISTENERS}
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CFG_CONTROLLER_QUORUM_VOTERS}
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: ${KAFKA_CFG_CONTROLLER_LISTENER_NAMES}
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: ${KAFKA_CFG_INTER_BROKER_LISTENER_NAME}
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL: ${KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL}
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: ${KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL}

    volumes:
      - ./certs/jks/${KAFKA_3_HOSTNAME}.server.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro
      - ./certs/jks/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro
